name = "tech10x"
compatibility_date = "2024-05-24"

[vars]
DATABASE_URL = ""
JWT_SECRET = ""


# R2_URL = "https://pub-96c5670691c8435283fb5dea0d94a7e8.r2.dev"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "HONO_R2_UPLOAD_TECH10x"
# bucket_name = "hono-r2-upload-tech10x"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
